# Generated by Django 5.1.5 on 2025-02-04 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
        migrations.AddField(
            model_name='email',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_email', to='mail.email', verbose_name='Родительское письмо'),
        ),
        migrations.AlterField(
            model_name='email',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Заархивировано'),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Тело письма'),
        ),
        migrations.AlterField(
            model_name='email',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_category', to='mail.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipients',
            field=models.CharField(max_length=4096, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(default='', max_length=255, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата письма'),
        ),
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
