# Generated by Django 5.1.6 on 2025-02-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_email_options_email_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='display_name',
            field=models.CharField(default='', max_length=255, verbose_name='Представление'),
        ),
    ]
