# Generated by Django 5.1.6 on 2025-02-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_email_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Вложение')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_attachments', to='mail.email', verbose_name='Письмо')),
            ],
        ),
    ]
