# Generated by Django 5.1.6 on 2025-02-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='name',
        ),
    ]
