# Generated by Django 5.1.6 on 2025-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_alter_attachment_options_remove_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Отправитель'),
        ),
    ]
